version: '3.4'

networks:
  database-network:
    driver: bridge
  register-microservice-api-network:
    driver: bridge
services: 
    web-mvc:
       image: ${DOCKER_REGISTRY-}webmvc
       build: 
         context: .
         dockerfile: src/Web/Web.MVC/Web.MVC/Dockerfile
       ports:
         - "1212:8080"
         - "1213:8081"
       environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:8081;http://+:8080
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Shi8Gb6vPznq
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/httpscertificate.pfx
       networks: 
         - register-microservice-api-network
       depends_on:
         - register-microservice-api
       volumes:
         - ~/.aspnet/https:/https:ro

    register-microservice-api:
      image: ${DOCKER_REGISTRY-}register-microservice-api
      build: 
        context: .
        dockerfile: src/Microservices/Register/RegisterMicroservice.Api/Dockerfile
      ports:
        - "2211:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
      networks: 
        - database-network
        - register-microservice-api-network
      depends_on:
        - postgres-db

    postgres-db:
       container_name: postgres
       image: postgres:latest
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: RegisterMicroservice
         POSTGRES_HOST: postgres-db
       ports: 
         - "5432:5432"
       networks:
         - database-network
       volumes: 
         - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:    