version: '3.4'

services: 
    web-mvc:
       image: ${DOCKER_REGISTRY-}webmvc
       build: 
         context: .
         dockerfile: src/Web/Web.MVC/Web.MVC/Dockerfile
       ports:
         - "1212:8080"
         - "1213:8081"
       environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:8081;http://+:8080
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Shi8Gb6vPznq
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/httpscertificate.pfx
       depends_on:
         - register-microservice-api
       volumes:
         - ~/.aspnet/https:/https:ro

    register-microservice-api:
      image: ${DOCKER_REGISTRY-}register-microservice-api
      build: 
        context: .
        dockerfile: src/Microservices/Register/RegisterMicroservice.Api/Dockerfile
      ports:
        - "2211:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
      depends_on:
        - postgres-register-microservice
        - rabbitmq

    user-microservice-api:
      image: ${DOCKER_REGISTRY-}user-microservice-api
      build:
        context: .
        dockerfile: src/Microservices/User/UserMicroservie.Api/Dockerfile
      ports:
        - "1122:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
      depends_on:
        - postgres-user-microservice
        - rabbitmq

    postgres-register-microservice:
       container_name: postgres-register-microservice
       image: postgres:latest
       expose:
        - 5432
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: RegisterMicroservice
         POSTGRES_HOST: postgres-register-microservice
       volumes: 
         - postgres-data:/var/lib/postgresql/data

    postgres-user-microservice:
       container_name: postgres-user-microservice
       image: postgres:latest
       expose:
        - 5432
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: UserMicroservice
         POSTGRES_HOST: postgres-user-microservice
       volumes: 
         - postgres-data:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:latest
        hostname: rabbitmq
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=rmuser
            - RABBITMQ_DEFAULT_PASS=rmpassword
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
volumes:
  postgres-data:    
    
