networks:
  database:
    driver: bridge
services: 
    register-microservice-api:
      container_name: register-microservice-api
      build: 
        context: .
        dockerfile: src/Microservices/Register/RegisterMicroservice.Api/Dockerfile
      ports:
        - "2211:8080"
        - "2323:8081"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080;https://+:8081
        - ASPNETCORE_Kestrel__Certificates__Default__Password=https
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      networks: 
        - database
      depends_on:
        - postgres-db
      volumes:
        - ~/.aspnet/https:/https:ro
    postgres-db:
       container_name: postgres
       image: postgres:latest
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: RegisterMicroservice
         POSTGRES_HOST: postgres-db
       ports: 
         - "5432:5432"
       networks:
         - database
       volumes: 
         - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:    